# I need a script that auto-generates README.md using the list of titles of all my posts
echo "README generated by autogen_readme script" > README.md
cat _posts/*.md | grep title | awk '{split($0,a,":"); print NR ". " a[2]}' >> README.md